=== openalea/agroservices/src/agroservices/data/ipm/schema_weatherdata.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Weather Data",
    "type": "object",
    "additionalProperties": false,
    "description": "Version 0.1. The schema describes the weather data format for the IPM Decisions platform. See an example here: https://platform.ipmdecisions.net/api/wx/rest/weatheradapter/yr/?longitude=14.3711&latitude=67.2828&altitude=70",
    "$id": "https://platform.ipmdecisions.net/api/wx/rest/schema/weatherdata",
    "properties": {
        "timeStart": {
            "type": "string",
            "format": "date-time",
            "description": "The timestamp of the first weather observation. Format: \"yyyy-MM-dd'T'HH:mm:ssXXX\", e.g. 2020-04-09T18:00:00+02:00",
            "title": "Time start (yyyy-MM-dd'T'HH:mm:ssXXX)"
        },
        "timeEnd": {
            "type": "string",
            "format": "date-time",
            "description": "The timestamp of the last weather observation. Format: \"yyyy-MM-dd'T'HH:mm:ssXXX\", e.g. 2020-04-09T18:00:00+02:00",
            "title": "Time end (yyyy-MM-dd'T'HH:mm:ssXXX)"
        },
        "interval": {
            "type": "integer",
            "description": "The sampling frequency in seconds. E.g. 3600 = hourly values",
            "title": "Sampling frequency (seconds)"
        },
        "weatherParameters": {
            "type": "array",
            "minItems": 1,
            "maxItems": 2147483647,
            "items": {
                "type": "integer"
            },
            "description": "The weather parameters. For reference, see https://platform.ipmdecisions.net/api/wx/rest/parameter",
            "title": "Weather parameters"
        },
        "locationWeatherData": {
            "oneOf": [
                {
                    "type": "null",
                    "title": "Not included"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LocationWeatherData"
                    }
                }
            ],
            "description": "The weather data per location.",
            "title": "Weather data"
        }
    },
    "required": [
        "timeStart",
        "timeEnd",
        "interval",
        "weatherParameters"
    ],
    "definitions": {
        "LocationWeatherData": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "longitude": {
                    "type": "number",
                    "description": "The longitude of the location. Decimal degrees (WGS84)",
                    "title": "Longitude (WGS84)"
                },
                "latitude": {
                    "type": "number",
                    "description": "The latitude of the location. Decimal degrees (WGS84)",
                    "title": "Latitude (WGS84)"
                },
                "altitude": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "number"
                        }
                    ],
                    "description": "The altitude of the location. Measured in meters",
                    "title": "Altitude (Meters)"
                },
                "qc": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    ]
                },
                "amalgamation": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    ]
                },
                "data": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included."
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "anyOf": [
                                        {
                                            "type": "number"
                                        },
                                        {
                                            "type": "null"
                                        }
                                    ]
                                }
                            }
                        }
                    ],
                    "description": "The data. In rows, ordered chronologically. Columns ordered as given in weatherParameters.",
                    "title": "Weather data per location"
                },
                "length": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "width": {
                    "oneOf": [
                        {
                            "type": "null",
                            "title": "Not included"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                }
            },
            "required": [
                "longitude",
                "latitude"
            ]
        }
    }
}

=== openalea/agroservices/test/weather_data.json
{
    "timeStart": "2020-10-02T08:00:00Z",
    "timeEnd": "2020-10-11T06:00:00Z",
    "interval": 3600,
    "weatherParameters": [
        1001,
        3001,
        2001,
        4002
    ],
    "locationWeatherData": [
        {
            "longitude": 14.3711,
            "latitude": 67.2828,
            "altitude": 70.0,
            "data": [
                [
                    13.5,
                    71.7,
                    0.0,
                    6.5
                ],
                [
                    14.1,
                    70.5,
                    0.0,
                    7.5
                ],
                [
                    14.7,
                    69.7,
                    0.0,
                    7.3
                ],
                [
                    15.3,
                    69.2,
                    0.0,
                    6.6
                ],
                [
                    15.6,
                    68.3,
                    0.0,
                    6.9
                ],
                [
                    15.3,
                    68.2,
                    0.0,
                    7.2
                ],
                [
                    15.0,
                    68.6,
                    0.0,
                    7.0
                ],
                [
                    14.3,
                    69.5,
                    0.0,
                    7.0
                ],
                [
                    13.5,
                    69.4,
                    0.0,
                    7.1
                ],
                [
                    12.8,
                    67.8,
                    0.0,
                    7.1
                ],
                [
                    12.4,
                    66.8,
                    0.0,
                    7.6
                ],
                [
                    12.1,
                    66.7,
                    0.0,
                    8.6
                ],
                [
                    11.8,
                    67.6,
                    0.0,
                    8.7
                ],
                [
                    11.7,
                    68.1,
                    0.0,
                    8.4
                ],
                [
                    11.5,
                    68.2,
                    0.0,
                    7.4
                ],
                [
                    11.4,
                    67.8,
                    0.0,
                    7.5
                ],
                [
                    11.2,
                    67.9,
                    0.0,
                    8.4
                ],
                [
                    11.0,
                    67.9,
                    0.0,
                    8.4
                ],
                [
                    10.9,
                    67.2,
                    0.0,
                    7.9
                ],
                [
                    10.7,
                    66.8,
                    0.0,
                    7.0
                ],
                [
                    10.6,
                    66.4,
                    0.0,
                    6.7
                ],
                [
                    10.5,
                    66.7,
                    0.0,
                    6.8
                ],
                [
                    10.5,
                    67.6,
                    0.0,
                    6.4
                ],
                [
                    10.9,
                    68.9,
                    0.0,
                    6.3
                ],
                [
                    11.7,
                    69.5,
                    0.0,
                    6.5
                ],
                [
                    12.6,
                    69.8,
                    0.0,
                    6.8
                ],
                [
                    13.3,
                    69.5,
                    0.0,
                    7.4
                ],
                [
                    13.8,
                    69.8,
                    0.0,
                    7.2
                ],
                [
                    14.0,
                    69.2,
                    0.0,
                    7.1
                ],
                [
                    13.9,
                    69.6,
                    0.0,
                    7.3
                ],
                [
                    13.6,
                    70.5,
                    0.0,
                    7.2
                ],
                [
                    13.1,
                    70.7,
                    0.0,
                    7.4
                ],
                [
                    12.4,
                    70.3,
                    0.0,
                    6.9
                ],
                [
                    11.8,
                    69.5,
                    0.0,
                    7.1
                ],
                [
                    11.4,
                    68.7,
                    0.0,
                    7.3
                ],
                [
                    11.1,
                    67.9,
                    0.0,
                    7.4
                ],
                [
                    10.9,
                    67.1,
                    0.0,
                    7.3
                ],
                [
                    10.8,
                    66.5,
                    0.0,
                    7.4
                ],
                [
                    10.7,
                    65.9,
                    0.0,
                    8.0
                ],
                [
                    10.7,
                    65.3,
                    0.0,
                    9.2
                ],
                [
                    10.5,
                    65.1,
                    0.0,
                    9.7
                ],
                [
                    10.4,
                    65.3,
                    0.0,
                    10.1
                ],
                [
                    10.1,
                    66.1,
                    0.0,
                    10.7
                ],
                [
                    9.9,
                    66.4,
                    0.0,
                    10.3
                ],
                [
                    9.9,
                    66.0,
                    0.0,
                    10.2
                ],
                [
                    9.9,
                    66.5,
                    0.0,
                    10.1
                ],
                [
                    9.9,
                    68.5,
                    0.0,
                    10.6
                ],
                [
                    10.4,
                    70.7,
                    0.0,
                    11.3
                ],
                [
                    11.0,
                    71.3,
                    0.0,
                    11.6
                ],
                [
                    11.8,
                    71.5,
                    0.0,
                    11.0
                ],
                [
                    12.5,
                    71.5,
                    0.0,
                    10.9
                ],
                [
                    13.1,
                    71.5,
                    0.0,
                    10.9
                ],
                [
                    13.4,
                    71.4,
                    0.0,
                    10.7
                ],
                [
                    13.083333333333334,
                    72.0,
                    0.0,
                    10.083333333333332
                ],
                [
                    12.766666666666667,
                    72.60000000000001,
                    0.0,
                    9.466666666666667
                ],
                [
                    12.45,
                    73.2,
                    0.0,
                    8.85
                ],
                [
                    12.133333333333333,
                    73.8,
                    0.0,
                    8.233333333333333
                ],
                [
                    11.816666666666666,
                    74.4,
                    0.0,
                    7.616666666666666
                ],
                [
                    11.5,
                    75.0,
                    0.0,
                    7.0
                ],
                [
                    11.383333333333333,
                    75.08333333333333,
                    0.0,
                    6.966666666666667
                ],
                [
                    11.266666666666667,
                    75.16666666666667,
                    0.0,
                    6.933333333333334
                ],
                [
                    11.15,
                    75.25,
                    0.0,
                    6.9
                ],
                [
                    11.033333333333333,
                    75.33333333333333,
                    0.0,
                    6.866666666666666
                ],
                [
                    10.916666666666668,
                    75.41666666666667,
                    0.0,
                    6.833333333333333
                ],
                [
                    10.8,
                    75.5,
                    0.0,
                    6.8
                ],
                [
                    10.783333333333333,
                    75.48333333333333,
                    0.0,
                    6.816666666666666
                ],
                [
                    10.766666666666667,
                    75.46666666666667,
                    0.0,
                    6.833333333333333
                ],
                [
